version: "3.0"
services:
  frontend:
    container_name: "gabaison-frontend"
    build:
      context: "."
      dockerfile: ./docker/frontend/dockerfile
    volumes:
      - ./front-app:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm run dev"
volumes:
  node_modules:

