version: "3.0"
services:
  frontend:
    container_name: "gabaison-frontend"
    build:
      context: "."
      dockerfile: ./docker/frontend/dockerfile
    volumes:
      - ./front-app:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm run dev"
  backend:
    container_name: "gabaison-backend"
    build:
      context: "."
      dockerfile: ./docker/backend/dockerfile
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
      TZ: "Asia/Tokyo"
volumes:
  node_modules:
  mysql_data:

